name: binder-kernel-test
channels:
  - conda-forge
dependencies:
  - python=3.8
  - qutip=4.5
  - matplotlib
  - scipy
  - numpy
  - ipykernel
  - pip
  - ipywidgets
  - jupyter_contrib_nbextensions
  - pip:
    - watermark
    - krotov
